### ISSUE TITLE
Can you host this app 

### ISSUE THREAD

**Issue by meshv-p** [sgoulas/pdpProject#7]
Hey @sgoulas  could you host this app so first I can see that app , lastly but not least that we get to know that where and how we can host full stack app.. so ...

**Comment by sgoulas** [comment]
Hello, if you want to host this app you should host the `server` folder somewhere and then change the `BACK_END_URL` constant in `src/api.constants.ts` from `http://localhost:4000/graphql` to the url the back end is deployed. Then you should probably create a vercel account, select the main branch as the deployment branch and it will be hosted automatically. The problem is hosting the back end somewhere.

As part of this project I did not have any plans to actually host the back end (initially I planned to mock the calls in the front end) so I am not sure how to do so. I may try to host the back end in the near future but I can't promise anything.

**Comment by sgoulas** [comment]
I uploaded [demo](https://www.youtube.com/watch?v=tExUzbz5eCY&ab_channel=SpyrosGoulas) that you can check out if you would like
